Implement max character check per token
xenova/transformers.js pull request #398
Opened 2023-11-16 22:17 UTC by samlhuillier

Returns unknown token for strings greater than param maxInputCharsPerWord (defaulting to 100). Fixes #397

2023-11-16 22:21 UTC, xenova commented on src/tokenizers.js
> +     * @param {number} [config.maxInputCharsPerWord=100] The maximum number of characters per word.
```suggestion
     * @param {number} [config.max_input_chars_per_word=100] The maximum number of characters per word.
```

2023-11-16 22:24 UTC, xenova requested changes
Thanks so much! Just note that the config is instantiated with the tokenizer.json, and as a result, relies on the exact same casing... which in this case, means it has to be `max_input_chars_per_word`

See https://huggingface.co/Xenova/bert-base-uncased/raw/main/tokenizer.json:
![image](https://github.com/xenova/transformers.js/assets/26504141/b790c5ee-1208-4441-9aed-2fef3effa368)

I also think it will be useful to add a test case for this [here](https://github.com/xenova/transformers.js/blob/main/tests/tokenizers.test.js#L42-L50), something like:
https://github.com/xenova/transformers.js/blob/4e4148cb5ce7f4a9265f58b4eeb660c64bed0386/tests/tokenizers.test.js#L42-L50.

2023-11-16 22:24 UTC, xenova commented on src/tokenizers.js
> +        this.maxInputCharsPerWord = config.maxInputCharsPerWord || 100;
```suggestion
        this.max_input_chars_per_word = config.max_input_chars_per_word ?? 100;
```

2023-11-16 22:24 UTC, xenova commented on src/tokenizers.js
> +            if (chars.length > this.maxInputCharsPerWord) {
```suggestion
            if (chars.length > this.max_input_chars_per_word) {
```

2023-11-16 22:24 UTC, xenova commented on src/tokenizers.js
> +     * @param {number} [config.maxInputCharsPerWord=100] The maximum number of characters per word.
```suggestion
     * @param {number} [config.max_input_chars_per_word=100] The maximum number of characters per word.
```

2023-11-17 19:48 UTC, merged

2023-11-17 19:55 UTC, xenova commented
Thanks so much! 🚀 The same output as the python library is obtained now:

```
It took  1.5605939999222755 ms to tokenize
Encoded:  [101,  100, 1009, 100, 1027, 1027, 102]
Decoded:  [CLS] [UNK] + [UNK] = = [SEP]
```
(and the time taken is now in the same range as the python library: 1.672983169555664ms)

2023-11-18 02:04 UTC, samlhuillier commented
Amazing! I shall update my package :)

2023-11-18 02:32 UTC, xenova commented
A new release (2.8.1) will be out shortly, but in the meantime, you can install from source (GitHub) if this fix is urgent.