Add StableLM support
xenova/transformers.js pull request #616
Opened 2024-03-01 10:25 UTC by D4ve-R

Adds support for `StableLMForCausalLM` & `StableLMForSequenceClassification`.  
Closes #549

2024-03-01 15:45 UTC, D4ve-R commented
StableLM support in Optimum is currently underway.  
https://github.com/huggingface/optimum/pull/1719

2024-03-01 21:11 UTC, xenova commented
I know it's still a draft, but I added a commit to get it into a working state :)

Example usage:
```js
import { pipeline } from '@xenova/transformers';

const generator = await pipeline('text-generation', 'Xenova/tiny-random-StableLmForCausalLM')
const output = await generator('hi')
console.log(output);
```

It's just a randomly initialized tiny model, so the output is gibberish. I will export some larger models too.

2024-03-01 21:13 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers.js/pr_616). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-03-02 10:49 UTC, D4ve-R commented
Awesome! 😎

2024-03-02 11:12 UTC, xenova commented
Yes that is how you do it - but luckily in this case, we already have a tiny stablelm model: https://huggingface.co/hf-internal-testing/tiny-random-StableLmForCausalLM (check out the [org](https://huggingface.co/hf-internal-testing) for the full list of them)

2024-03-02 12:37 UTC, xenova commented
Here are some of the larger models:
- https://huggingface.co/Xenova/stablelm-2-1_6b
- https://huggingface.co/Xenova/stablelm-2-zephyr-1_6b

which we can test with

([see all](https://huggingface.co/models?library=transformers.js&other=stablelm))

2024-03-02 13:52 UTC, xenova commented
Seems to work alright! 👍 

```js
import { pipeline } from '@xenova/transformers';

const generator = await pipeline('text-generation', 'Xenova/stablelm-2-zephyr-1_6b')

const prompt = [{'role': 'user', 'content': 'Tell me a joke'}];
const inputs = generator.tokenizer.apply_chat_template(prompt, { add_generation_prompt: true, tokenize: false });

const output = await generator(inputs, { max_new_tokens: 20 })
console.log(output[0].generated_text);
// "<|user|>\nTell me a joke\n<|assistant|>\nWhy did the tomato turn red?\n\nBecause it saw the salad dressing!"
```

2024-03-03 14:42 UTC, D4ve-R commented
Really cool! Will turn this into a pr.

2024-03-03 15:20 UTC, xenova commented
Thanks! I think the last thing to do is just export and test with some sequence classifier models. Is that something you'd like to work on?

2024-03-06 11:11 UTC, xenova commented
Looks like there aren't any stablelm text-classification models on the [HF Hub](https://huggingface.co/models?pipeline_tag=text-classification&other=stablelm&sort=trending) (other than your test of course). So I think it will be a good idea to move that to a separate PR and get this merged?
![image](https://github.com/xenova/transformers.js/assets/26504141/f15c3906-8692-46d5-8fe9-e62f107f91de)

2024-03-06 11:13 UTC, xenova requested changes
TODO: move stablelm text classification to separate PR

2024-03-06 11:13 UTC, xenova commented on src/models.js
> +
```suggestion
```

2024-03-06 11:13 UTC, xenova commented on src/models.js
> +    ['stablelm', ['StableLMForSequenceClassification', StableLMForSequenceClassification]],
```suggestion
```

2024-03-06 11:13 UTC, xenova commented on src/models.js
> +
```suggestion
```

2024-03-06 12:55 UTC, D4ve-R commented
Wow, seems like you can read my mind 😆
You're right, will move this to another PR!
My response i had typed in, but not send yet:  


Little update, since there is currently no stablelm model for text classification on the hub, I tried training my own.
Unfortunately I was unable to train on 16GB T4. I will add the code below to train [`stablelm-2-1_6b`](https://huggingface.co/stabilityai/stablelm-2-1_6b) on [`twitter-financial-news-sentiment`](https://huggingface.co/datasets/zeroshot/twitter-financial-news-sentiment), if somebody wants to give it a shot.
I think we should split this in two seperate prs and merged the Seq Classification one when a model is available.

```python
import numpy as np
from datasets import load_dataset
from transformers import AutoTokenizer, DataCollatorWithPadding, AutoModelForSequenceClassification, TrainingArguments, Trainer
import evaluate
from huggingface_hub import login
login()

dataset = "zeroshot/twitter-financial-news-sentiment"
model = "stabilityai/stablelm-2-1_6b"

dataset = load_dataset(dataset)
tokenizer = AutoTokenizer.from_pretrained(model)
tokenizer.pad_token = tokenizer.eos_token
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)
accuracy = evaluate.load("accuracy")

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    return accuracy.compute(predictions=predictions, references=labels)

def preprocess_function(examples):
    return tokenizer(examples["text"], truncation=True)

tokenized_dataset = dataset.map(preprocess_function, batched=True)
id2label = {0: "Bearish", 1: "Bullish", 2: "Neutral"}
label2id = {"Bearish": 0, "Bullish": 1, "Neutral": 2}

model = AutoModelForSequenceClassification.from_pretrained(
    model,
    num_labels=len(id2label),
    id2label=id2label,
    label2id=label2id,
)
model.config.pad_token_id = model.config.eos_token_id

training_args = TrainingArguments(
    output_dir="stablelm-2-1_6b-sentiment",
    learning_rate=2e-5,
    # TODO: will it fit 16GB?
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=2,
    weight_decay=0.01,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    # TODO: will it fit 16GB?
    gradient_accumulation_steps=4,
    gradient_checkpointing=True,
    optim="adamw_bnb_8bit",
    load_best_model_at_end=True,
    push_to_hub=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer.train()
trainer.push_to_hub()
```

2024-03-06 15:35 UTC, xenova commented on src/models.js
> +     * @param {Object} config The configuration of the model.
```suggestion
// StableLM models
export class StableLmPreTrainedModel extends PreTrainedModel {
    /**
     * Creates a new instance of the `StableLmPreTrainedModel` class.
     * @param {Object} config The configuration of the model.
```

2024-03-06 15:35 UTC, xenova commented on src/models.js
> +// StableLM models
```suggestion
// StableLm models
```

2024-03-06 15:35 UTC, xenova commented on src/models.js
> +export class StableLMForCausalLM extends StableLMPreTrainedModel {
```suggestion
/**
 * The bare StableLM Model transformer outputting raw hidden-states without any specific head on top.
 */
export class StableLMModel extends StableLMPreTrainedModel { }

/**
 * StableLm Model with a `language modeling` head on top for Causal Language Modeling (with past).
 */
export class StableLmForCausalLM extends StableLmPreTrainedModel {
```

2024-03-06 15:35 UTC, xenova commented on src/models.js
> +    ['stablelm', ['StableLMForCausalLM', StableLMForCausalLM]],
```suggestion
    ['stablelm', ['StableLmForCausalLM', StableLmForCausalLM]],
```

2024-03-06 15:39 UTC, xenova reviewed
naming nits

2024-03-06 15:39 UTC, xenova commented on src/models.js
> +export class StableLMPreTrainedModel extends PreTrainedModel {
```suggestion
export class StableLmPreTrainedModel extends PreTrainedModel {
```

2024-03-06 15:39 UTC, xenova commented on src/models.js
> +     * Creates a new instance of the `StableLMPreTrainedModel` class.
```suggestion
     * Creates a new instance of the `StableLmPreTrainedModel` class.
```

2024-03-06 15:39 UTC, xenova commented on src/models.js
> +
```suggestion
/**
 * The bare StableLm Model transformer outputting raw hidden-states without any specific head on top.
 */
export class StableLmModel extends StableLmPreTrainedModel { }

```

2024-03-07 01:01 UTC, xenova commented on scripts/convert.py
> +    },
```suggestion
    'stablelm': {
        'per_channel': False,
        'reduce_range': False,
    },
```

2024-03-07 01:03 UTC, xenova commented on src/models.js
> +}
```suggestion
export class StableLmForCausalLM extends StableLmPreTrainedModel { }
```

2024-03-07 01:05 UTC, merged

2024-03-07 01:22 UTC, xenova commented
Merged! Thanks for this @D4ve-R! 🤗 


**Example:** Text generation with `Xenova/stablelm-2-zephyr-1_6b`.

```js
import { pipeline } from '@xenova/transformers';

// Create text generation pipeline
const generator = await pipeline('text-generation', 'Xenova/stablelm-2-zephyr-1_6b');

// Define the prompt and list of messages
const prompt = "Tell me a funny joke."
const messages = [
    { "role": "system", "content": "You are a helpful assistant." },
    { "role": "user", "content": prompt },
]

// Apply chat template
const inputs = generator.tokenizer.apply_chat_template(messages, {
    tokenize: false,
    add_generation_prompt: true,
});

// Generate text
const output = await generator(inputs, { max_new_tokens: 20 });
console.log(output[0].generated_text);
// "<|system|>\nYou are a helpful assistant.\n<|user|>\nTell me a funny joke.\n<|assistant|>\nHere's a joke for you:\n\nWhy don't scientists trust atoms?\n\nBecause they make up everything!"
```